### ISSUE TITLE
vipcApply Docs Show Incorrect Format of LV Version

### ISSUE THREAD

**Issue by JamesWiresmith** [LabVIEW-DCAF/buildsystem#16]
the vipcApply comment on the diagram says that it should be the LabVIEW version as the parameter e.g. 2014.

the API actually needs the "proper"(?) version e.g 14.0

**Comment by JamesWiresmith** [comment]
This may need more testing. Now that I do what the API actually requests I get other errors!

**Comment by JamesWiresmith** [comment]
Apologies completely ignore me! You have that handled in the script - must be another fault that I am seeing (VIPC isn't installing packages properly).

**Comment by pollockm** [comment]
First make sure you have VIPM pro licensed on that machine.  The JKI API unfortunately fails to give a good error message if it is not licensed.

**Comment by JamesWiresmith** [comment]
It is licensed but not sure what is going on.

Basically it runs for a seemingly appropriate time but when I launch VIPM manually it lists the packages but not as installed. After retrying it has now been running for 2hrs - maybe it is doing something?!

**Comment by pollockm** [comment]
Forgetting the step wrapper, does using the JKI API function to Apply VIPC File work?
You might want to disable the quiet mode input on that function to see what it is doing.

If you are running Jenkins in headless mode (i.e., running the agent as a system service), you might be in a scenario where VIPM is waiting for you to clear a dialog.  Try running your agent as a user, not a system service, and you might get more clues.

**Comment by JamesWiresmith** [comment]
That's part of it, think the JKI Update was blocking. I already had the service setup as a user but if I was logged in as that user as well I could not see Jenkins processes (even with show from all).

Logged in from another user and I could see it waiting there. I also could exit from Jenkins again now? Will look into that.

Running it directly, before I saw it working so assumed it would go through, turns out one of the packages has a post build step with a dialog - that probably the main issue. Hoping if I install it once then the prompt wont show again.
