### ISSUE TITLE
Package files can have versions of previously published packages.

### ISSUE THREAD

**Issue by theSloopJohnB** [LabVIEW-DCAF/buildsystem#17]
[Build 12](http://vm-dcaf-bld-14:8080/job/LabVIEW-DCAF/job/TagEditorCore/job/master/12/console) of master TagEditorCore published a package versioned 2.4.0.13. 

The problem was that in the unstable repository there already was a package with that version produced by [build 6](http://vm-dcaf-bld-14:8080/job/LabVIEW-DCAF/job/TagEditorCore/job/master/6/).

It looks like the new one was never published and the old one remained.

Ideally a higher version number should be produced.

**Comment by theSloopJohnB** [comment]
This has happened again with this build: http://vm-dcaf-bld-14:8080/job/LabVIEW-DCAF/job/TagEditorCore/job/ErrorCfg/1/console

**Comment by pollockm** [comment]
Found root cause.  Fixing now. @theSloopJohnB
