### ISSUE TITLE
Builds Failing On UTF Step "Error Receiving Header"

### ISSUE THREAD

**Issue by jacobson3** [LabVIEW-DCAF/buildsystem#41]
Latest builds for J1939 and Modbus Modules are both failing at run-utf step, reporting the following error.

_Error receiving header: Header bytes missing, received 0 of 4 bytes_

I am able to run the same labview-cli step from the command line on a virtual machine with the following packages without any errors.
LV CLI 1.5.0.8
CLI Common Steps 1.0.2.19

**Comment by pollockm** [comment]
The build machines are using LV CLI 1.2.0.1 and common steps 1.0.2.19.

I'll try updating the build machines.

**Comment by pollockm** [comment]
@jacobson3  Looks like that fixed it, at least for Modbus.

**Comment by pollockm** [comment]
@jacobson3  - J1939 also makes it through.

**Comment by jacobson3** [comment]
Awesome, thanks for kicking off the builds as well.

**Comment by pollockm** [comment]
No problemo.  I will mark this as closed.
