### ISSUE TITLE
CONTRIBUTION doc

### ISSUE THREAD

**Issue by hoffiz** [LabVIEW-DCAF/buildsystem#45]
What version of LabVIEW are the Steps compiled in? When working on these VIs how is your system configured?

**Comment by pollockm** [comment]
2014.  All of DCAF is on 2014.

**Comment by hoffiz** [comment]
It should be added to the README or on a CONTRIBUTION doc.

**Comment by pollockm** [comment]
Fixed in https://github.com/LabVIEW-DCAF/buildsystem/pull/49
