### ISSUE TITLE
Get rid of the extra 'ignore this commit' commit from buildsystem

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/buildsystem#8]
Find a way to squash the commits such that we can combine the source modification commit and the version bump commit.  Having half of the commit history in master being 'ignore' seems like something that should be a solved problem out there.

I'm okay with the commit history including that in the branches, also ok with appending a message to the existing commit.  Just don't want worthless commits clogging the master log if we can avoid it.

**Comment by smithed** [comment]
I think you guys arent using it anymore but I believe my build function bumped the build number to match the jenkins number (which always autoincrements) without actually saving the vip. If you change the code enough to make that a major or minor version bump you'd go in and do that yourself. Probably a safer way would be to fetch the version list from the vip repo and take the max of highest-avail-build+1 and current-jenkins-build-number. In either case, you don't have to have the autobuilder commit anything ever (which I would argue it shouldn't). 

If you have your heart set on autobuilder commits I think you just need to have it do this:
http://stackoverflow.com/questions/5667884/how-to-squash-commits-in-git-after-they-have-been-pushed

**Comment by pollockm** [comment]
That method (use Jenkins build number) was great...until we needed to restore backups of the build server, which reset the build numbers and caused all kinds of exciting havoc.

I do like the idea of scanning the version numbers published in the internal repository - that would give us better protection against build server changes.

**Comment by pollockm** [comment]
Implemented in background server.  Removed build step of committing updated vipb in https://github.com/LabVIEW-DCAF/buildsystem/commit/437e941e517e846137d212eeece3a7a15731f070

**Comment by pollockm** [comment]
We don't use the Jenkins build number because feature branches would use the branch's build number, which is usually much lower than the overall package build.
